# Generated by Django 5.1 on 2024-09-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_alter_usuario_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialmedico',
            name='acompanante',
            field=models.CharField(default=False, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historialmedico',
            name='antecedentes',
            field=models.TextField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historialmedico',
            name='color',
            field=models.CharField(default=False, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historialmedico',
            name='diagnostico',
            field=models.TextField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historialmedico',
            name='dieta',
            field=models.TextField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historialmedico',
            name='esterilizado',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historialmedico',
            name='frecuencia_cardiaca',
            field=models.IntegerField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historialmedico',
            name='frecuencia_respiratoria',
            field=models.IntegerField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historialmedico',
            name='partos',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historialmedico',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historialmedico',
            name='temperatura',
            field=models.DecimalField(decimal_places=1, default=False, max_digits=4),
            preserve_default=False,
        ),
    ]
