# Generated by Django 5.1 on 2024-09-16 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_remove_historialmedico_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialmedico',
            name='resultado',
        ),
    ]
