# Generated by Django 5.1 on 2024-09-16 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0007_remove_historialmedico_estado_animal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to=settings.AUTH_USER_MODEL),
        ),
    ]
